### ISSUE TITLE
Consolidate `waitForCompletion` and `__2`

### ISSUE THREAD

**Issue by dehann** [NavAbility/NavAbilitySDK.jl#142]
currently under `NVA.waitForCompletion2` which we can consolidate before tagging.  Will create new issue for that.

_Originally posted by @dehann in https://github.com/NavAbility/NavAbilitySDK.jl/issues/141#issuecomment-1213471188_

**Comment by dehann** [comment]
Hi @jim-hill-r , how's it going with the migration to new eventing.  I was looking for the ticket on the Tactical board, but didn't immediately see it.

**Comment by jim-hill-r** [comment]
I think it would be safe to just check both endpoints at the same time and if both fail then fail, if one succeeds, then return success. No need for two signatures.

**Comment by Affie** [comment]
Obsolete with cloud v4
