### ISSUE TITLE
add testing for deleteFactor

### ISSUE THREAD

**Issue by dehann** [NavAbility/NavAbilitySDK.jl#160]
we should remember to add testing for deleteFactor

_Originally posted by @dehann in https://github.com/NavAbility/NavAbilitySDK.jl/issues/158#issuecomment-1244024686_

**Comment by Affie** [comment]
What is wrong with the tests I wrote?

**Comment by Affie** [comment]
Oops, I never pushed the test, but now the branch is deleted.
