### ISSUE TITLE
Ensure Point2 is generated properly by SDK

### ISSUE THREAD

**Issue by jim-hill-r** [NavAbility/NavAbilitySDK.jl#35]
When choosing RoME.Point2 as the VariableType in SDK, the cloud cannot support it for some reason.

The following error occurs: `BoundsError([6.94616648028127e-310, 2.121995791e-314], [1, 2, 3]`

To reproduce:
- Change type from RoME.Pose2 to RoME.Point2 in `testVariable.jl`
- Start local cloud via `npm start` in `cloud-system` root
- Change apiUrl to `http://localhost:4343`
- Run `julia --project=. ./test/integration/runtests.jl`

**Comment by GearsAD** [comment]
Resolve in https://github.com/NavAbility/NavAbilitySDK.jl/pull/73
