### ISSUE TITLE
ContinuousScalar is not supported in the SDK

### ISSUE THREAD

**Issue by GearsAD** [NavAbility/NavAbilitySDK.jl#65]
As a user I would like to be able to create a ContinuousScalar and have it initialize the VariableData correctly (at the moment it is forced to creating a Pose2-format structure, which causes a BoundsError when it is loaded into the cloud). 

## TAC
- Add ContinousScalar to the supported VariableTypes
- Parametrize the VariableNodeData so that it initializes correctly for each type
- Add unit tests to validate operation

**Comment by jim-hill-r** [comment]
This is in IIF right? If so, should work as long as you can produce the PackedVariable payload.

**Comment by GearsAD** [comment]
No this requires significant refactoring, I'll make these changes in a bit.
