### ISSUE TITLE
Rayleigh, Normal, and Uniform distributions are not supported in the SDK

### ISSUE THREAD

**Issue by GearsAD** [NavAbility/NavAbilitySDK.jl#67]
As a user I would like to be able to use the Uniform, Normal, and Rayleigh distributions in Factors.

This is needed in the Mixture factor in the ICRA Tutorial 2 example.

**Comment by jim-hill-r** [comment]
Which packages contains these factors? RoME, IIF, something else?

**Comment by dehann** [comment]
- Uniform, Normal, Rayleigh, `AMP.ManifoldKernelDensity` etc are `Distributions` which for which serialization is mostly held in IIF.
- Factors are `Pose2Pose2`, `PriorPose2`, etc.

`IIF.Mixture` currently has inverse API than what it should have, so I'm toying with the idea of fixing that before we hack at the Data model Sam mentioned.
- JuliaRobotics/Caesar.jl#808
