### ISSUE TITLE
apiUrl will change in medium term, using dev default for now

### ISSUE THREAD

**Issue by dehann** [NavAbility/NavAbilitySDK.jl#84]
Context: Sam and I are putting together on call the Tut1 1000 solves using sessions on the cloud with this SDK.jl.

Small observation to reduce friction, could we use default `apiUrl`:
```julia

NavAbilityHttpsClient(apiUrl="https://api.d1.navability.io")
```

**Comment by jim-hill-r** [comment]
We can. The only reason I didn't was technically the default should be https://api.navability.io but that doesn't exist yet, so was waiting for that.

**Comment by dehann** [comment]
Cool, lets resolve in future PR release.  I'm going to add this for now.
